### ISSUE TITLE
Problem running graphql-qb-0.1.0-standalone.jar

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#22]
I created the jar file using `lein uberjar`

Ther  run the jar `java -jar graphql-qb-0.1.0-SNAPSHOT.jar 9898` and get an exception

```
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/lang/Var
        at graphql_qb.main.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: clojure.lang.Var
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```
Any ideas?

**Comment by RickMoynihan** [comment]
Hi Dimitris, that is the library jar.  The uberjar (application jar) should be named `graphql-qb-0.1.0-SNAPSHOT-standalone.jar`, if you use that one it should work.

**Comment by zeginis** [comment]
Yes that works fine. 
Thank you.
