### ISSUE TITLE
Filtering observations - Time out exception 

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#87]
```
{
  dataset_births {
    observations(dimensions: {gender: MALE, 
                              reference_period:{starts_after:  "2000-01-01T00:00:00Z"
                                                ends_before: "2001-01-01T00:00:00Z"}}) {
      page(first: 20) {
        observations {
          reference_area {
            label
            uri
          }
          reference_period {
            start
            end
            label
          }
        }
      }
    }
  }
}
```

**Comment by mohadelrezk** [comment]
is this work for any temporal dimension?

**Comment by zeginis** [comment]
@mohadelrezk  I have made some testing. The following query works fine. You can use it for testing if you want:

```
{dataset_average_household_size{
  observations(dimensions:{reference_period:{starts_after:  "2015-01-01T00:00:00Z"}}){
    page(first:50){
      observations{
        ratio
        reference_area {
          label
          uri
        }
        reference_period {
          end
          label
          start
          uri
        }
        
      }
    }
  }
}}
```

**Comment by zeginis** [comment]
Indeed optional is the problem.
A solution could be what you have proposed, however we have not decided yet to use measureType on every observation. 

Taking this problem as motive, I think it is importan to agree on the data model to use (e.g. always use measure type), since all pilot data should be created/transformed based on this model.

@RicSwirrl btw how did you extracted the SPARQL query created by CubiQL? I need this to debug some other issues.

**Comment by zeginis** [comment]
An alternative to the solution you proposed:
```
?obs <http://purl.org/linked-data/cube#measureType> ?mp .
?obs ?mp ?mv
```
Would be (without the use of measureType):
```
?obs ?mp ?mv.
?mp a qb:MeasureProperty.
```

Both cases, however, return all the measures even if the user asks for some of them. For example at a cube with measures: `count`, `ratio`, `mean `a user may needs only the `ratio` and `mean`. In this case we could also add:
`?obs <http://statistics.gov.scot/def/measure-properties/ratio>|<http://statistics.gov.scot/def/measure-properties/mean> ?mv.`

I have tried using a FILTER clause but there were also time out exceptions e.g.
`FILTER(?mp IN(<http://statistics.gov.scot/def/measure-properties/ratio> <http://statistics.gov.scot/def/measure-properties/mean>))`

**Comment by zeginis** [comment]
@RicSwirrl A quick fix would be to just remove `OPTIONAL`

In this case CubiQL queries could ask only for **one** measure even if there are more.
However, the SPARQL query should contain **only the measure requested**. Currently SPARQL queries contain all the measures (and all dimensions) even if they are not requested.

e.g. the CubiQL query:
```
{
dataset_deaths{
  observations{
    page{
      observations{
        count
}}}}}
```
Generates the SPARQL:
```
PREFIX qb: <http://purl.org/linked-data/cube#>
SELECT * WHERE {  ?obs  a qb:Observation . 
  ?obs  qb:dataSet <http://statistics.gov.scot/data/deaths> .
  ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?dim1 . 
  ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?dim2 . 
  ?obs <http://purl.org/linked-data/cube#measureType> ?dim3 .
  ?obs <http://statistics.gov.scot/def/dimension/gender> ?dim4 .
  ?obs <http://statistics.gov.scot/def/dimension/age> ?dim5 .
  ?obs <http://statistics.gov.scot/def/dimension/causeOfDeath> ?dim6 .
  ?obs <http://statistics.gov.scot/def/dimension/year> ?dim7 . 
  OPTIONAL { ?obs <http://statistics.gov.scot/def/measure-properties/ratio> ?mv1 . }
  OPTIONAL { ?obs <http://statistics.gov.scot/def/measure-properties/count> ?mv2 . }}
```
The proposed SPARQL would be:
```
PREFIX qb: <http://purl.org/linked-data/cube#>
SELECT * WHERE {  ?obs  a qb:Observation . 
  ?obs  qb:dataSet <http://statistics.gov.scot/data/deaths> .
  ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?dim1 . 
  ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?dim2 . 
  ?obs <http://purl.org/linked-data/cube#measureType> ?dim3 .
  ?obs <http://statistics.gov.scot/def/dimension/gender> ?dim4 .
  ?obs <http://statistics.gov.scot/def/dimension/age> ?dim5 .
  ?obs <http://statistics.gov.scot/def/dimension/causeOfDeath> ?dim6 .
  ?obs <http://statistics.gov.scot/def/dimension/year> ?dim7 . 
  ?obs <http://statistics.gov.scot/def/measure-properties/count> ?mv1 . 
  }
```
We can also leave out all the dimension triples (e.g. refArea, refPeriod, gender etc.)

**Comment by zeginis** [comment]
@lkitching I am trying to solve this issue but there is not much documentation on the code to understand how bindings are treated at the code.

I would like to create SPARQL statements like this:
```
?obs <http://purl.org/linked-data/cube#measureType> ?mp .
?obs ?mp ?mv
```

I changed the code for the measure type at `types.clj`
```
(defrecord MeasureType [uri label order is-numeric?]
  ...
  SparqlResultProjector
  (apply-projection [_this model selections]
    (let [dim-key (keyword (str "mv" order))
           dim-value (keyword (str "mp" order))]
       (let [model (qm/add-binding model [[dim-value (URI. "http://purl.org/linked-data/cube#measureType")]] ::qm/var)
             model (qm/add-binding model [[dim-key dim-value]] ::qm/var)]
         model)))    
```

But I get an exception when running the code. Any idea what causes the exception and how can be solved?

```
clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException in Interceptor :com.walmartlabs.lacinia.pedestal/query-executor - No implementation of method: :query-format of protocol: #'graphql-qb.query-model/QueryItem found for class: clojure.lang.Keyword
	at clojure.core$ex_info.invokeStatic(core.clj:4739) ~[clojure-1.9.0.jar:?]
	at clojure.core$ex_info.invoke(core.clj:4739) ~[clojure-1.9.0.jar:?]
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invokeStatic(chain.clj:35) ~[?:?]
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invoke(chain.clj:32) ~[?:?]
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:57) ~[?:?]
	at io.pedestal.interceptor.chain$try_f.invoke(chain.clj:44) ~[?:?]
	at io.pedestal.interceptor.chain$process_all_with_binding.invokeStatic(chain.clj:171) ~[?:?]
	at io.pedestal.interceptor.chain$process_all_with_binding.invoke(chain.clj:146) ~[?:?]
	at io.pedestal.interceptor.chain$process_all$fn__17645.invoke(chain.clj:188) ~[?:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) ~[clojure-1.9.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.9.0.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:?]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965) ~[clojure-1.9.0.jar:?]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965) ~[clojure-1.9.0.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:425) ~[clojure-1.9.0.jar:?]
	at io.pedestal.interceptor.chain$process_all.invokeStatic(chain.clj:186) ~[?:?]
	at io.pedestal.interceptor.chain$process_all.invoke(chain.clj:182) ~[?:?]
	at io.pedestal.interceptor.chain$enter_all.invokeStatic(chain.clj:235) ~[?:?]
	at io.pedestal.interceptor.chain$enter_all.invoke(chain.clj:229) ~[?:?]
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:379) [?:?]
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352) [?:?]
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:389) [?:?]
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352) [?:?]
	at io.pedestal.http.impl.servlet_interceptor$interceptor_service_fn$fn__21889.invoke(servlet_interceptor.clj:350) [?:?]
	at io.pedestal.http.servlet.FnServlet.service(servlet.clj:28) [?:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838) [jetty-servlet-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) [jetty-servlet-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) [jetty-servlet-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112) [jetty-io-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.0.v20161208.jar:9.4.0.v20161208]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.0.v20161208.jar:9.4.0.v20161208]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.IllegalArgumentException: No implementation of method: :query-format of protocol: #'graphql-qb.query-model/QueryItem found for class: clojure.lang.Keyword
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583) ~[clojure-1.9.0.jar:?]
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575) ~[clojure-1.9.0.jar:?]
	at graphql_qb.query_model$eval5457$fn__5458$G__5448__5463.invoke(query_model.clj:11) ~[?:?]
	at graphql_qb.query_model$format_query_triple_pattern.invokeStatic(query_model.clj:148) ~[?:?]
	at graphql_qb.query_model$format_query_triple_pattern.invoke(query_model.clj:147) ~[?:?]
	at clojure.core$map$fn__5587.invoke(core.clj:2747) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:?]
	at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.9.0.jar:?]
	at clojure.lang.RT.next(RT.java:706) ~[clojure-1.9.0.jar:?]
	at clojure.core$next__5108.invokeStatic(core.clj:64) ~[clojure-1.9.0.jar:?]
	at clojure.string$join.invokeStatic(string.clj:191) ~[clojure-1.9.0.jar:?]
	at clojure.string$join.invoke(string.clj:180) ~[clojure-1.9.0.jar:?]
	at graphql_qb.query_model$get_query.invokeStatic(query_model.clj:177) ~[?:?]
	at graphql_qb.query_model$get_query.invoke(query_model.clj:167) ~[?:?]
	at graphql_qb.queries$get_observation_query.invokeStatic(queries.clj:33) ~[?:?]
	at graphql_qb.queries$get_observation_query.invoke(queries.clj:31) ~[?:?]
	at graphql_qb.queries$get_observation_page_query.invokeStatic(queries.clj:37) ~[?:?]
	at graphql_qb.queries$get_observation_page_query.invoke(queries.clj:35) ~[?:?]
	at graphql_qb.resolvers$inner_resolve_observations_page.invokeStatic(resolvers.clj:102) ~[?:?]
	at graphql_qb.resolvers$inner_resolve_observations_page.invoke(resolvers.clj:96) ~[?:?]
	at graphql_qb.resolvers$wrap_pagination_resolver$fn__6498.invoke(resolvers.clj:90) ~[?:?]
	at graphql_qb.schema$wrap_observations_mapping$fn__6653.invoke(schema.clj:59) ~[?:?]
	at com.walmartlabs.lacinia.schema$wrap_resolver_to_ensure_resolver_result$fn__3656.invoke(schema.clj:519) ~[?:?]
	at com.walmartlabs.lacinia.executor$invoke_resolver_for_field.invokeStatic(executor.clj:114) ~[?:?]
	at com.walmartlabs.lacinia.executor$invoke_resolver_for_field.invoke(executor.clj:86) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select.invokeStatic(executor.clj:421) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select.invoke(executor.clj:319) ~[?:?]
	at com.walmartlabs.lacinia.executor$eval5149$fn__5150.invoke(executor.clj:203) ~[?:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.9.0.jar:?]
	at com.walmartlabs.lacinia.executor$maybe_apply_selection.invokeStatic(executor.clj:257) ~[?:?]
	at com.walmartlabs.lacinia.executor$maybe_apply_selection.invoke(executor.clj:253) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections$fn__5174.invoke(executor.clj:281) ~[?:?]
	at clojure.core$keep$fn__8200.invoke(core.clj:7261) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:?]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:?]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:?]
	at clojure.core$reduce.invoke(core.clj:6730) ~[clojure-1.9.0.jar:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections.invokeStatic(executor.clj:282) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections.invoke(executor.clj:273) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select$selector_callback__5219.invoke(executor.clj:344) ~[?:?]
	at com.walmartlabs.lacinia.schema$floor_selector.invokeStatic(schema.clj:528) ~[?:?]
	at com.walmartlabs.lacinia.schema$floor_selector.invoke(schema.clj:525) ~[?:?]
	at com.walmartlabs.lacinia.schema$create_root_selector$select_unwrap_tagged_type__3668.invoke(schema.clj:614) ~[?:?]
	at com.walmartlabs.lacinia.schema$create_root_selector$select_apply_static_type__3670.invoke(schema.clj:619) ~[?:?]
	at com.walmartlabs.lacinia.schema$create_root_selector$select_require_single_value__3673.invoke(schema.clj:627) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select$process_resolved_value__5226.invoke(executor.clj:385) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select$receive_resolved_value_from_field__5228.invoke(executor.clj:423) ~[?:?]
	at com.walmartlabs.lacinia.resolve.ResolverResultImpl.on_deliver_BANG_(resolve.clj:94) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select.invokeStatic(executor.clj:421) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select.invoke(executor.clj:319) ~[?:?]
	at com.walmartlabs.lacinia.executor$eval5149$fn__5150.invoke(executor.clj:203) ~[?:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.9.0.jar:?]
	at com.walmartlabs.lacinia.executor$maybe_apply_selection.invokeStatic(executor.clj:257) ~[?:?]
	at com.walmartlabs.lacinia.executor$maybe_apply_selection.invoke(executor.clj:253) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections$fn__5174.invoke(executor.clj:281) ~[?:?]
	at clojure.core$keep$fn__8200.invoke(core.clj:7257) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:?]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:?]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:?]
	at clojure.core$reduce.invoke(core.clj:6730) ~[clojure-1.9.0.jar:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections.invokeStatic(executor.clj:282) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections.invoke(executor.clj:273) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select$selector_callback__5219.invoke(executor.clj:344) ~[?:?]
	at com.walmartlabs.lacinia.schema$floor_selector.invokeStatic(schema.clj:528) ~[?:?]
	at com.walmartlabs.lacinia.schema$floor_selector.invoke(schema.clj:525) ~[?:?]
	at com.walmartlabs.lacinia.schema$create_root_selector$select_unwrap_tagged_type__3668.invoke(schema.clj:614) ~[?:?]
	at com.walmartlabs.lacinia.schema$create_root_selector$select_apply_static_type__3670.invoke(schema.clj:619) ~[?:?]
	at com.walmartlabs.lacinia.schema$create_root_selector$select_require_single_value__3673.invoke(schema.clj:627) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select$process_resolved_value__5226.invoke(executor.clj:385) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select$receive_resolved_value_from_field__5228.invoke(executor.clj:423) ~[?:?]
	at com.walmartlabs.lacinia.resolve.ResolverResultImpl.on_deliver_BANG_(resolve.clj:94) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select.invokeStatic(executor.clj:421) ~[?:?]
	at com.walmartlabs.lacinia.executor$resolve_and_select.invoke(executor.clj:319) ~[?:?]
	at com.walmartlabs.lacinia.executor$eval5149$fn__5150.invoke(executor.clj:203) ~[?:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[clojure-1.9.0.jar:?]
	at com.walmartlabs.lacinia.executor$maybe_apply_selection.invokeStatic(executor.clj:257) ~[?:?]
	at com.walmartlabs.lacinia.executor$maybe_apply_selection.invoke(executor.clj:253) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections$fn__5174.invoke(executor.clj:281) ~[?:?]
	at clojure.core$keep$fn__8200.invoke(core.clj:7257) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:?]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:?]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:?]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:?]
	at clojure.core$reduce.invoke(core.clj:6730) ~[clojure-1.9.0.jar:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections.invokeStatic(executor.clj:282) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_nested_selections.invoke(executor.clj:273) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_query.invokeStatic(executor.clj:454) ~[?:?]
	at com.walmartlabs.lacinia.executor$execute_query.invoke(executor.clj:428) ~[?:?]
	at com.walmartlabs.lacinia.pedestal$execute_query.invokeStatic(pedestal.clj:239) ~[?:?]
	at com.walmartlabs.lacinia.pedestal$execute_query.invoke(pedestal.clj:234) ~[?:?]
	at com.walmartlabs.lacinia.pedestal$fn__23320.invokeStatic(pedestal.clj:254) ~[?:?]
	at com.walmartlabs.lacinia.pedestal$fn__23320.invoke(pedestal.clj:253) ~[?:?]
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:54) ~[?:?]
	... 39 more
```

**Comment by lkitching** [comment]
@zeginis - Sorry for the delay in getting back to you. If you want to generate a var in the predicate position you need to use the `QueryVar` record e.g.

```clojure
(-> empty-model
      (add-binding [[:mp (URI. "http://purl.org/linked-data/cube#measureType")]] ::qm/var)
      (add-binding [[:mv (->QueryVar "mp")]] ::qm/var)
      (get-query "obs" (URI. "http://dataset")))
```

generates the query

```
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT * WHERE {  
  ?obs  a qb:Observation .  
  ?obs  qb:dataSet <http://ds> .
  ?obs <http://purl.org/linked-data/cube#measureType> ?mp . 
  ?obs ?mp ?mv .
}
```

Since we want to find the measure type for the observation, I think we'll need to add the `?mp` var at a higher level than `MeasureType`, then only return a value for each measure type if the value bound to `?mp` matches the measure type URI. Something like:

```clojure
    (defrecord MeasureType [uri ...]
      SparqlResultProjector
        (apply-projection [_this model selections]
          model)

        (project-result [_this binding]
          (if (= uri (get binding :mp))
            (get binding :mv))))
```

**Comment by zeginis** [comment]
Thank you @lkitching I'll give it a try!

**Comment by zeginis** [comment]
@lkitching what do you mean with higher level? 
Where should we define the `?mp` var? At the `SparqlResultProjector`?

**Comment by RickMoynihan** [comment]
Sorry @zeginis @lkitching is away today - will ask him to provide more info when he's back next week.

**Comment by lkitching** [comment]
@zeginis - Sorry, I meant we can't add the graph patterns for `?obs <http://purl.org/linked-data/cube#measureType> ?mp . ?obs ?mp ?mv` in the `MeasureType` record implementation. Looking at the code, I think we can put it in `queries/get-observation-filter-model` since we want it to apply to all the queries e.g.

```clojure
(defn get-observation-filter-model [dim-filter]
   (let [m (-> qm/empty-model
                    (add-binding [[:mp (URI. "http://purl.org/linked-data/cube#measureType")]] ::qm/var)
                    (add-binding [[:mv (->QueryVar "mp")]] ::qm/var))]
       (reduce (fn [m [dim value]]
                       (types/apply-filter dim m value))
                     m
                     dim-filter))))
```

**Comment by zeginis** [comment]
@lkitching  thank you. I have tried what you have proposed. The SPARQL created is correct, however I get the same value for both the count and ratio. e.g.

```
{ "ratio": "20.15",
   "count": "20.15"
 }
```

I have changed the MeasureType as you have proposed:
```
(defrecord MeasureType [uri ...]
      SparqlResultProjector
        (apply-projection [_this model selections]
          model)

        (project-result [_this binding]
          (if (= uri (get binding :mp))
            (get binding :mv))))
```

**Comment by zeginis** [comment]
@lkitching I think we shoul also add the check   `(if (= uri (get binding :mp))` at the `MeasureType -> get-result-projection`. However bindings are not accessible at the `get-result-projection` any idea how to fix this?

**Comment by lkitching** [comment]
@zeginis - Could you push this to a branch so I can take a look? Do your observations have multiple measures associated with them? We might need to change the way the query model stuff works to do this properly.

**Comment by zeginis** [comment]
@lkitching  I have pushed the code here: https://github.com/zeginis/graphql-qb/tree/FixTimeout

I use the Scotish endpoint so each observation has only one measure. However the Dataset has two measures.

**Comment by zeginis** [comment]
@lkitching I think the problem is that the `types.clj->MeasureType->get-result-projection` is executed for both the MeasureTypes of the Dataset even if there is only one measure at the observation.

```
(get-result-projection [_this]
    (let [dim-key (keyword (str "mv"))]
      (->PathProjection [[dim-key uri]] true identity)))
```

One solution would be to add a check like this: `(if (= uri (get binding :mp))` however the bindings are not accessible at the `get-result-projection`. 

Any idea how to fix this?

**Comment by zeginis** [comment]
I fixed that. I created a PR that solves this issue.
